In [3]:
import numpy as np
x = np.linspace(0,10,50) 
x

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [7]:
y = np.random.random(50)
y

array([0.26705169, 0.38388898, 0.92875827, 0.55907238, 0.26618281,
       0.06706268, 0.6161391 , 0.16798957, 0.08640659, 0.84115661,
       0.59221401, 0.89077653, 0.93562895, 0.4137795 , 0.96738409,
       0.73490669, 0.6154936 , 0.48930039, 0.9437516 , 0.24199339,
       0.26028165, 0.15153614, 0.25134789, 0.94355116, 0.24646466,
       0.18074837, 0.60568653, 0.60499941, 0.88400256, 0.67351246,
       0.11112597, 0.78311264, 0.48314598, 0.11783732, 0.20407573,
       0.79477518, 0.83034296, 0.41171252, 0.37575948, 0.03092087,
       0.1556587 , 0.45252219, 0.35462942, 0.02367621, 0.80036042,
       0.59098214, 0.01155049, 0.82067907, 0.09457652, 0.43698828])

In [11]:
z = x+y 
z

array([ 0.26705169,  0.58797061,  1.33692153,  1.17131728,  1.08250934,
        1.08747084,  1.8406289 ,  1.596561  ,  1.71905965,  2.6778913 ,
        2.63303034,  3.13567449,  3.38460854,  3.06684072,  3.82452695,
        3.79613118,  3.88079972,  3.95868814,  4.61722099,  4.11954441,
        4.3419143 ,  4.43725043,  4.7411438 ,  5.63742871,  5.14442384,
        5.28278919,  5.91180898,  6.1152035 ,  6.59828828,  6.59187981,
        6.23357495,  7.10964325,  7.01375823,  6.8525312 ,  7.14285124,
        7.93763232,  8.17728173,  7.96273293,  8.13086152,  7.99010455,
        8.31892401,  8.81986913,  8.92605799,  8.79918641,  9.77995226,
        9.77465561,  9.39930559, 10.4125158 ,  9.89049489, 10.43698828])

In [13]:
somma = sum(z)
somma

273.69550035346214

In [15]:
z[z>5]

array([ 5.63742871,  5.14442384,  5.28278919,  5.91180898,  6.1152035 ,
        6.59828828,  6.59187981,  6.23357495,  7.10964325,  7.01375823,
        6.8525312 ,  7.14285124,  7.93763232,  8.17728173,  7.96273293,
        8.13086152,  7.99010455,  8.31892401,  8.81986913,  8.92605799,
        8.79918641,  9.77995226,  9.77465561,  9.39930559, 10.4125158 ,
        9.89049489, 10.43698828])

In [19]:
somma5 = sum(z[z>5])
somma5

210.39074419949196

In [21]:
x,y,z, somma, somma5

(array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
         1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
         2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
         3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
         4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
         5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
         6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
         7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
         8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
         9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ]),
 array([0.26705169, 0.38388898, 0.92875827, 0.55907238, 0.26618281,
        0.06706268, 0.6161391 , 0.16798957, 0.08640659, 0.84115661,
        0.59221401, 0.89077653, 0.93562895, 0.4137795 , 0.96738409,
        0.73490669, 0.6154936 , 0.48930039, 0.9437516 , 0.241993