In [5]:
import numpy as np
x = np.linspace(0,1,12)
x

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

In [15]:
x = x.reshape(3,4)
x

array([[0.        , 0.09090909, 0.18181818, 0.27272727],
       [0.36363636, 0.45454545, 0.54545455, 0.63636364],
       [0.72727273, 0.81818182, 0.90909091, 1.        ]])

In [27]:
A = np.random.rand(3,4)
A

array([[0.45197892, 0.88757145, 0.9989649 , 0.68680464],
       [0.99729723, 0.97024624, 0.78671781, 0.91848933],
       [0.34641366, 0.80751423, 0.05410223, 0.70113242]])