In [16]:
import numpy as nd
arr = nd.random.randint(1,101,36)
arr

array([99, 29, 99, 29,  4, 69, 18, 15, 10, 26, 47,  9, 68, 67, 68, 39, 48,
       58, 73, 71, 22, 81, 85, 22, 69, 70, 74, 12, 66, 76, 38, 54, 99, 98,
       43,  7])

In [18]:
arr = arr.reshape(6,6)
arr

array([[99, 29, 99, 29,  4, 69],
       [18, 15, 10, 26, 47,  9],
       [68, 67, 68, 39, 48, 58],
       [73, 71, 22, 81, 85, 22],
       [69, 70, 74, 12, 66, 76],
       [38, 54, 99, 98, 43,  7]])

In [36]:
arr_s=arr[1:5, 1:5]
arr_s 


array([[15, 10, 26, 47],
       [67, 68, 39, 48],
       [71, 22, 81, 85],
       [70, 74, 12, 66]])

In [56]:
arr_i = arr_s[::-1, :]
arr_i

array([[70, 74, 12, 66],
       [71, 22, 81, 85],
       [67, 68, 39, 48],
       [15, 10, 26, 47]])

In [60]:
diagonale = diag(arr_i,0)

NameError: name 'diag' is not defined